examples:
  - example/*
  - example/**/*

Formik:
  - packages/formik/src/Formik.tsx
  - packages/formik/test/Formik.test.tsx

Field:
  - packages/formik/src/Field.tsx
  - packages/formik/test/Field.test.tsx

Form:
  - packages/formik/src/Form.tsx
  - packages/formik/test/Form.test.tsx

FastField:
  - packages/formik/src/FastField.tsx
  - packages/formik/test/FastField.test.tsx

FieldArray:
  - packages/formik/src/FieldArray.tsx
  - packages/formik/test/FieldArray.test.tsx

ErrorMessage:
  - packages/formik/src/ErrorMessage.tsx
  - packages/formik/test/ErrorMessage.test.tsx

withFormik:
  - packages/formik/src/withFormik.tsx
  - packages/formik/test/withFormik.t.testsx

utils:
  - packages/formik/src/utils.ts
  - packages/formik/test/util.tests.ts

cypress:
  - cypress/*
  - cypress/**/*

docs:
  - ./docs/*
  - ./docs/**

repo:
  - ./*
