examples:
  - example/*
  - example/**/*

'Component: Formik':
  - packages/formik/src/Formik.tsx
  - packages/formik/test/Formik.test.tsx

'Component: Field':
  - packages/formik/src/Field.tsx
  - packages/formik/test/Field.test.tsx

'Component: Form':
  - packages/formik/src/Form.tsx
  - packages/formik/test/Form.test.tsx

'Component: FastField':
  - packages/formik/src/FastField.tsx
  - packages/formik/test/FastField.test.tsx

'Component: FieldArray':
  - packages/formik/src/FieldArray.tsx
  - packages/formik/test/FieldArray.test.tsx

'Component: ErrorMessage':
  - packages/formik/src/ErrorMessage.tsx
  - packages/formik/test/ErrorMessage.test.tsx

'Component: withFormik':
  - packages/formik/src/withFormik.tsx
  - packages/formik/test/withFormik.t.testsx

cypress:
  - cypress/*
  - cypress/**/*

docs:
  - ./docs/*
  - ./docs/**
