language: node_js
node_js:
  - '8'
env:
  - CI=true

script:
  - yarn test -- --runInBand --no-cache --coverage

deploy:
  provider: script
  script: curl -X POST -d '' $NETLIFY_BUILD_HOOK
  skip_cleanup: true
  on:
    branch: master