name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['10.x', '12.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install yarn package manager
        run: npm install -g yarn

      - name: Install deps and build
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --runInBand --no-cache --coverage
