name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['10.x', '12.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install yarn package manager
        run: npm install -g yarn

      - name: Install deps and build
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --runInBand --no-cache --coverage

  docs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Ping Netlify to trigger rebuild
        if: github.ref == 'master'
        run: curl -X POST -d {} ${{ secrets.NETLIFY_URL }}
