name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarnpkg
        run: npm i -g yarn

      - name: Install deps and build package
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --runInBand --no-cache --coverage

  docs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Ping Netlify to trigger rebuild
        if: github.ref == 'master'
        run: curl -X POST -d {} ${{ secrets.NETLIFY_URL }}
