name: Publish

on:
  push:
    branches:
      - canary

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, test, Publish
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          CI: true
      - name: Publish to npm
        run: yarn run lerna publish from-git --npm-tag canary --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
