name: Publish Canary

on:
  push:
    branches:
      - canary

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          CI: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish canary to NPM
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - name: Publish
        run: yarn run lerna publish from-git --npm-tag canary --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
